// app/layout.tsx
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

import { ToastContainer } from "@/components/ui/molecules/Toast"
import { ThemeProvider } from '@/components/ui/layout/ThemeProvider'
import { StripeWrapper } from '@/components/ui/payments/StripeWrapper';

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'Cognitiva',
  description: 'Generated by Cognitiva',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider   
          attribute="class"
          defaultTheme="system"
          enableSystem>
          <StripeWrapper>
            {children}
          </StripeWrapper>
          <ToastContainer />
        </ThemeProvider>
      </body>
    </html>
  )
}